### PR TITLE
(work in progress) Added adfs screenshots, updated okta policy section

### PR DESCRIPTION
**Pull request by gabecase**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/staging.horse/build-936ce0cf5d/docs/rackspace-federation/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/staging.horse/build-b74033232e/docs/rackspace-federation/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/staging.horse/build-e7830bd907/docs/rackspace-federation/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/staging.horse/build-2f6b1d46c0/docs/rackspace-federation/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/staging.horse/build-4af4590c70/docs/rackspace-federation/)

**Comment by catlook** [comment]
This was split into other PRs, so I'm deep-sixing it

**Pull request closed without merging**
