### PR TITLE
Change TOC order and some errors

### PR DESCRIPTION
**Pull request by rtgoodwin**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/staging.horse/build-68c7209f9d/docs/rackspace-federation/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-07b5e22064/docs/rackspace-federation/)

**Comment by rtgoodwin** [comment]
Updated some Okta stuff.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/staging.horse/build-36a6c5e47e/docs/rackspace-federation/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/staging.horse/build-6e8ab6405b/docs/rackspace-federation/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/staging.horse/build-d7f09f8ab0/docs/rackspace-federation/)

**Pull request merged**
