### PR TITLE
Fix the toc

### PR DESCRIPTION
**Pull request by catlook**
Fixing the behavior where the side nav goes away when clicking on the top level on side nav

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-48516517ca/docs/rackspace-federation/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-c8df9810a6/docs/rackspace-federation/).

**Comment by catlook** [comment]
This puppy isn't ready to merge yet..in progress

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-a84deac563/docs/rackspace-federation/). :bow:

**Pull request merged**
