### PR TITLE
Initial reorg and troubleshoot

### PR DESCRIPTION
**Pull request by catlook**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 26 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-8571ada7a/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 27 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-933e39f3a/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 28 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f5ed34ddc/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 30 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-77c7b3ed2/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 31 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-fc16f6e6b/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 32 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b95491c5f/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 33 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ffc7f6781/docs/rackspace-federation/). valid for 14 days

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 34 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ffc7f6781/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 35 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3b2712f3e/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 43 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ace413353/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 46 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3cff4ef97/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 47 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-08d6f1093/docs/rackspace-federation/). valid for 14 days

**Comment by gabecase** [comment]
LGTM

**Pull request merged**
