### PR TITLE
update attribute policy section

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 114 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-750ab764e/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 115 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ff71b388f/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 116 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a53966fa0/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 117 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-489b130b6/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 118 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-282495591/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 119 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-7da4c9cad/docs/rackspace-federation/). valid for 14 days

**Comment by WilliamLoy** [comment]
@cyrichardson would you please edit if you have time? :)

**Comment by cyrichardson** [comment]
On it, @WilliamLoy.

**Comment by rackernexus** [comment]
Build 120 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-4bc49fded/docs/rackspace-federation/). valid for 14 days

**Comment by cyrichardson** [comment]
@WilliamLoy Edits complete! Please review them and see if you agree with them. Thanks!

**Comment by rackernexus** [comment]
Build 121 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-db51dde7b/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 122 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-db51dde7b/docs/rackspace-federation/). valid for 14 days

**Comment by WilliamLoy** [comment]
LGTM

**Pull request merged**
