### PR TITLE
first push to check formatting

### PR DESCRIPTION
**Pull request by catlook**
need to check example formatting

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 51 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b98b70adb/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 52 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f10e6d964/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 53 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c8833eb83/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 54 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e494568eb/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 55 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b770d0e12/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 56 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f90980210/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 57 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-0dd5468d3/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 58 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e59a713d9/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 59 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-2131ffe80/docs/rackspace-federation/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 62 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-0c086b173/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 63 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-0c086b173/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 64 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-0c086b173/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 65 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-0c086b173/docs/rackspace-federation/). valid for 14 days

**Comment by rackernexus** [comment]
Build 66 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-0c086b173/docs/rackspace-federation/). valid for 14 days

**Pull request merged**
