### PR TITLE
Add scoped faws observer and admin examples to attrib mapping policy

### PR DESCRIPTION
**Pull request by ltvolks**
We may want to see if this is documented more broadly elsewhere and incorporate that, but until then we can provide this basic example

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-ab5f7d72ae/docs/rackspace-federation/)

**Comment by gabecase** [comment]
I think adding a short snippet like your example in the description is good since configuring multiple aws accounts would be a common use case

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-ab5f7d72ae/docs/rackspace-federation/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-78ce19317e/docs/rackspace-federation/)

**Comment by ltvolks** [comment]
@gabecase Updated w/ an example of mapping to multiple AWS accounts

**Pull request merged**
