### PR TITLE
[do not merge] test build

### PR DESCRIPTION
**Pull request by nimbinatus**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by rackernexus** [comment]
Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/staging.horse/build-5070ff8303/docs/rackspace-federation/). :bow:

**Comment by nimbinatus** [comment]
build now working. closing PR

**Pull request closed without merging**
